//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2-70- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.02.26 at 10:31:45 PM IST 
//


package objectmodel;

import java.util.ArrayList;
import java.util.List;
import java.util.Random;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence maxOccurs="unbounded">
 *         &lt;element name="BonusCard" type="{}BonusCard"/>
 *       &lt;/sequence>
 *       &lt;attribute name="Type" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="Community Chest"/>
 *             &lt;enumeration value="Chance"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "bonusCard"
})
@XmlRootElement(name = "CardsDeck")
public class CardsDeck {

    @XmlElement(name = "BonusCard", required = true)
    protected List<BonusCard> bonusCard;
    @XmlAttribute(name = "Type", required = true)
    protected String type;

    /**
     * Gets the value of the bonusCard property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the bonusCard property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBonusCard().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BonusCard }
     * 
     * 
     */
    public List<BonusCard> getBonusCard() {
        if (bonusCard == null) {
            bonusCard = new ArrayList<BonusCard>();
        }
        return this.bonusCard;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }
    
    public void shuffleDeck()
    {
    	Random rand = new Random();
    	BonusCard tempCard;
    	
    	for (int i = 0; i<(2 * bonusCard.size()); i++)
    	{
    		int shufflePositionA = rand.nextInt(bonusCard.size());
    		int shufflePositionB = rand.nextInt(bonusCard.size());
    		
    		tempCard = bonusCard.get(shufflePositionA);
    		bonusCard.set(shufflePositionA, bonusCard.get(shufflePositionB));
    		bonusCard.set(shufflePositionB, tempCard);
    	}
    }
    
    public BonusCard drawCard()
    {
    	return bonusCard.remove(0);
    }
    
    public void returnCard(BonusCard returnedCard)
    {
    	bonusCard.add(returnedCard);
    }
}
