//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2-70- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.02.26 at 10:31:45 PM IST 
//


package objectmodel;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link City }
     * 
     */
    public City createCity() {
        return new City();
    }

    /**
     * Create an instance of {@link Player }
     * 
     */
    public Player createPlayer() {
        return new Player();
    }

    /**
     * Create an instance of {@link CardsDeck }
     * 
     */
    public CardsDeck createCardsDeck() {
        return new CardsDeck();
    }

    /**
     * Create an instance of {@link BonusCard }
     * 
     */
    public BonusCard createBonusCard() {
        return new BonusCard();
    }

    /**
     * Create an instance of {@link GameBoard }
     * 
     */
    public GameBoard createGameBoard() {
        return new GameBoard();
    }

    /**
     * Create an instance of {@link CellBase }
     * 
     */
    public CellBase createCellBase() {
        return new CellBase();
    }

    /**
     * Create an instance of {@link Assets }
     * 
     */
    public Assets createAssets() {
        return new Assets();
    }

    /**
     * Create an instance of {@link Asset }
     * 
     */
    public Asset createAsset() {
        return new Asset();
    }

    /**
     * Create an instance of {@link Country }
     * 
     */
    public Country createCountry() {
        return new Country();
    }

    /**
     * Create an instance of {@link Group }
     * 
     */
    public Group createGroup() {
        return new Group();
    }

    /**
     * Create an instance of {@link City.HouseToll }
     * 
     */
    public City.HouseToll createCityHouseToll() {
        return new City.HouseToll();
    }

    /**
     * Create an instance of {@link Player.OwnedCells }
     * 
     */
    public Player.OwnedCells createPlayerOwnedCells() {
        return new Player.OwnedCells();
    }

    /**
     * Create an instance of {@link Player.OwnedCards }
     * 
     */
    public Player.OwnedCards createPlayerOwnedCards() {
        return new Player.OwnedCards();
    }

}
