//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2-70- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.03.04 at 11:17:17 AM IST 
//


package objectmodel;

import Utils.WaitNotifyManager;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import main.StateManager;
import main.UserPrompt;
import monopoly.results.PlayerDetailsResult;

/**
 * <p>Java class for Player complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Player">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="OwnedCells">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *                   &lt;element name="Cell" type="{}CellBase"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="OwnedCards">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *                   &lt;element name="Card" type="{}BonusCard"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="Name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Money" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="BoardPosition" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="IsInGame" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Player", propOrder = {
    "ownedCells",
    "ownedCards",
    "inputObject",
    "playerActions"
})
public class Player
{	
	private static final int INITIAL_MONEY = 1500;
	private static final int MAX_AUCTION_COUNT = 3;
	
	public Player()
	{
		setMoney(INITIAL_MONEY);
		isInGame = true;
		isInJail = false;
		isParking = false;
		auctionsPerformed = 0;
		ownedCards = new OwnedCards();
		ownedCells = new OwnedCells();
	}

    @XmlElement(name = "OwnedCells", required = true)
    protected Player.OwnedCells ownedCells;
    @XmlElement(name = "OwnedCards", required = true)
    protected Player.OwnedCards ownedCards;
    @XmlAttribute(name = "Name", required = true)
    protected String name;
    @XmlAttribute(name = "Money", required = true)
    protected int money;
    @XmlAttribute(name = "BoardPosition", required = true)
    protected int boardPosition;
    @XmlAttribute(name = "IsInGame", required = true)
    protected boolean isInGame;
    @XmlElement(name = "InputObject", required = false)
    protected PlayerInput inputObject;
    @XmlElement(name = "PlayerActions", required = false)
    protected PlayerActions playerActions;
    @XmlAttribute(name = "IsInJail", required = false)
    protected boolean isInJail;
    @XmlAttribute(name = "IsParking", required = false)
    protected boolean isParking;
    @XmlAttribute(name = "auctionsPerformed", required = false)
    protected int auctionsPerformed;
    @XmlAttribute(name = "resignRequested", required = false)
    private boolean resignRequested = false;
    
    public boolean canPerformAuction()
    {
    	return (auctionsPerformed < MAX_AUCTION_COUNT);
    }
    
    public void raiseAuctionPerformed()
    {
    	auctionsPerformed ++;
    }
    
    public boolean addMoney(int money)
    {
    	if (money < 0)
    	{
    		return false;
    	}
    	
    	this.money += money;
    	return true;
    }
    
    public int subtractMoney(int money)
    {
    	if (money < 0)
    	{
    		return 0;
    	}
    	if (money > this.money)
    	{
    		this.money = 0;
    		return money - this.money;
    	}
    	
    	this.money -= money;
    	return 0;
    }

	public boolean isInJail() {
		return isInJail;
	}

	public void setInJail(boolean isInJail) {
		this.isInJail = isInJail;
	}

	public boolean isParking() {
		return isParking;
	}

	public void setParking(boolean isParking) {
		this.isParking = isParking;
	}

	public PlayerInput getInputObject() {
		return inputObject;
	}

	public void setInputObject(PlayerInput inputObject) {
		this.inputObject = inputObject;
	}
	
	public PlayerActions getPlayerActions() {
		return playerActions;
	}

	public void setPlayerActions(PlayerActions playerActions) {
		this.playerActions = playerActions;
	}

	/**
     * Gets the value of the ownedCells property.
     * 
     * @return
     *     possible object is
     *     {@link Player.OwnedCells }
     *     
     */
    public Player.OwnedCells getOwnedCells() {
        return ownedCells;
    }

    /**
     * Sets the value of the ownedCells property.
     * 
     * @param value
     *     allowed object is
     *     {@link Player.OwnedCells }
     *     
     */
    public void setOwnedCells(Player.OwnedCells value) {
        this.ownedCells = value;
    }

    /**
     * Gets the value of the ownedCards property.
     * 
     * @return
     *     possible object is
     *     {@link Player.OwnedCards }
     *     
     */
    public Player.OwnedCards getOwnedCards() {
        return ownedCards;
    }

    /**
     * Sets the value of the ownedCards property.
     * 
     * @param value
     *     allowed object is
     *     {@link Player.OwnedCards }
     *     
     */
    public void setOwnedCards(Player.OwnedCards value) {
        this.ownedCards = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the money property.
     * 
     */
    public int getMoney() {
        return money;
    }

    /**
     * Sets the value of the money property.
     * 
     */
    public void setMoney(int value) {
        this.money = value;
    }

    /**
     * Gets the value of the boardPosition property.
     * 
     */
    public int getBoardPosition() {
        return boardPosition;
    }

    /**
     * Sets the value of the boardPosition property.
     * 
     */
    public void setBoardPosition(int value) {
        this.boardPosition = value;
    }

    /**
     * Gets the value of the isInGame property.
     * 
     */
    public boolean isInGame() {
        return isInGame;
    }

    /**
     * Sets the value of the isInGame property.
     * 
     */
    public void setIsInGame(boolean value) {
        this.isInGame = value;
    }

    /**
     * enables a player to resign from the game
     */
    public void RequestToResign()
    {
        this.resignRequested = true;
    }

    /**
     * returns true if the player requested to resign
     */
    public boolean WasResignRequested()
    {
        return this.resignRequested;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
     *         &lt;element name="Card" type="{}BonusCard"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "card"
    })
    public static class OwnedCards {

        @XmlElement(name = "Card")
        protected List<BonusCard> card;

        /**
         * Gets the value of the card property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the card property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCard().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link BonusCard }
         * 
         * 
         */
        public List<BonusCard> getCard() {
            if (card == null) {
                card = new ArrayList<BonusCard>();
            }
            return this.card;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
     *         &lt;element name="Cell" type="{}CellBase"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "cell"
    })
    public static class OwnedCells {

        @XmlElement(name = "Cell")
        protected List<CellBase> cell;

        /**
         * Gets the value of the cell property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the cell property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCell().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link CellBase }
         * 
         * 
         */
        public List<CellBase> getCell() {
            if (cell == null) {
                cell = new ArrayList<CellBase>();
            }
            return this.cell;
        }
    }
}
